### ISSUE TITLE
Module on Powershell Core

### ISSUE THREAD

**Issue by pianogen** [mkellerman/Invoke-CommandAs#41]
Hello 

I've installed this module on Powershell Core for Linux. Powershell has imported successfully the module, but when I put the command in a powershell session I receive an error message, thath the term Invoke-CommandAs has not been recognized.

Is this module designed only for Powershell Desk on Windows?

Best Regards
Gennaro Piano

**Comment by janegilring** [comment]
I did the same and got this message:
Invoke-ScheduledTask : The term 'Register-ScheduledJob' is not recognized as the name of a cmdlet, function, script file, or operable program.

Since the module leverages PSScheduledJobs which is not available in Core/7 I think it only works on Windows PowerShell.

**Comment by mkellerman** [comment]
Correct, this is for windows only.
I haven't tested running this from a Linux machine against a Windows machine.

I dont have any linux environments to test with, but if anyone wants to help implement a linux compatible version of this, let me know.
